### ISSUE TITLE
Inställningen "reply-to" skrivs över vid synkning

### ISSUE THREAD

**Issue by h-lindberg** [Scouterna/Google-Scoutnet-synk#52]
Vi har problem med att inställningen vi har valt på respektive grupp under "Gruppinställningar>E-postalternativ>Lägg upp svar till" skrivs över vid synkning.

Jag har lyckats hitta raden som är orsaken till detta, 1033 i Grupper.gs - kan jag bara kommentera bort denna eller kommer jag få andra problem då?

Det ultimata hade varit om standardinställningen på nya listor är "endast meddelandets författare", men att inställningen får vara kvar om den skrivs över via Google Grupper.

**Comment by webbmastern** [comment]
Hej,
Det går bra att kommentera bort raden men du kommer behöva göra inställningen för reply-to för alla nya grupper.
Standardvärdet om inget sätts i koden är i skrivande stund REPLY_TO_IGNORE men inget är definerat enligt dokumentationen https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups#resource . Jag har ej testat hur REPLY_TO_IGNORE blir i praktiken när det gäller e-postlistor.

Jag kan kolla på att göra så att avsändaren sätts som reply-to som standard men att det sen går att ändra.
Skulle du kunna ge något exempel när det är lämpligt med något annat än som det är nu så jag får en förståelse hur viktigt detta är?

De olika inställningar som är möjliga att göra är följande
- **REPLY_TO_CUSTOM**: For replies to messages, use the group's custom email address.
When the group's ReplyTo property is set to REPLY_TO_CUSTOM, the customReplyTo property holds the custom email address used when replying to a message. If the group's ReplyTo property is set to REPLY_TO_CUSTOM, the customReplyTo property must have a value. Otherwise an error is returned.
- **REPLY_TO_SENDER**: The reply sent to author of message.
- **REPLY_TO_LIST**: This reply message is sent to the group.
- **REPLY_TO_OWNER**: The reply is sent to the owner(s) of the group. This does not include the group's managers.
- **REPLY_TO_IGNORE**: Group users individually decide where the message reply is sent.
- **REPLY_TO_MANAGERS**: This reply message is sent to the group's managers, which includes all managers and the group owner.
